### ISSUE TITLE
Remove or put this somewhere else

### ISSUE THREAD

**Issue by TroyCalaquian** [COMP2522/project-cactus-club#111]
https://github.com/COMP2522/project-cactus-club/blob/a55e24f504c6550cb517ed86f43152207fe107e3/src/main/java/cactus/slabslayer/Ball.java#L309

Because you're checking this in the game loader already, it feels redundant to do this. Even then, this suggests that you are passing the whole json array in the class

**Comment by JVViacrusis** [comment]
Necessary
