### ISSUE TITLE
Change the timing of the save

### ISSUE THREAD

**Issue by TroyCalaquian** [COMP2522/project-cactus-club#112]
https://github.com/COMP2522/project-cactus-club/blob/a55e24f504c6550cb517ed86f43152207fe107e3/src/main/java/cactus/slabslayer/GameSaveHandler.java#L60

If you do plan on adding a pause button to this game, you can load the latest save. However, because it isn't every second, if you do grab the save, it'll go back a couple of seconds, which is something you might not want

**Comment by JVViacrusis** [comment]
Pausing will not be done this way. Save timing will not be changed
