### ISSUE TITLE
Design 3 levels of differing styles and choose a style as a team.

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-cactus-club#13]
Design 3 levels with differing size, difficulty, and aesthetic. The team will choose, and have later levels be made in that style.

During this design process, take note of any GameElements that should seem to be necessary to the game and be ready to present an arugment for it's necessity despite it's development cost.

**Comment by CyrusVillaruz** [comment]
![20230320_144641.jpg](https://user-images.githubusercontent.com/91701334/226474025-85b77c97-304b-4f99-acec-ca0548cb0724.jpg)

![20230320_143902.jpg](https://user-images.githubusercontent.com/91701334/226474026-d7091d37-d03c-4a47-a63d-7fdab38ae0c8.jpg)

I have drawn some sample level designs. The arrows in the "Complex Variants" indicate moving slabs

**Comment by JVViacrusis** [comment]
Nice! can you make a couple with closer to 40-50+ pieces? might be easier to do so digitally but feel free to do them on paper again

**Comment by CyrusVillaruz** [comment]
Here are some more sample designs. There's only one moving slab example level, since getting a base implementation seems to be more important right now. I also put to the right of the level the themes of levels with the designs.

![20230322_132639.jpg](https://user-images.githubusercontent.com/91701334/227030464-872fa4d4-2c9a-4e25-b61c-d252b9c98ef1.jpg)

![20230322_132645.jpg](https://user-images.githubusercontent.com/91701334/227030465-3824b0a2-6a1a-4962-a484-5ad83b3e58d4.jpg)

**Comment by JVViacrusis** [comment]
I'm liking the second batch a lot more. Seeing as you already made 5 in this larger style, if there are no conflicting opinions on choosing this style over the previous style, I'll go ahead and close #14 too.

I'll leave this issue up for another couple hours to let any more opinions come in

**Comment by justshye** [comment]
I like the second batch more too, but the "Mazes/Labyrinths" level feels like it could end up with the user doing absolutely nothing for 2 minutes - which is satisfying to some but might be boring to others

**Comment by JVViacrusis** [comment]
Accidental close. My previous comment still stands

**Comment by NicRodri** [comment]
I like the second batch more as well. Levels have more character to them

**Comment by JVViacrusis** [comment]
Alright looks like everyone agrees on the last 5 designs. Since @CyrusVillaruz already made 5, I'll be closing #14
