### ISSUE TITLE
Do a pass for magic numbers, e.g. in below

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-cactus-club#135]
https://github.com/COMP2522/project-cactus-club/blob/a55e24f504c6550cb517ed86f43152207fe107e3/src/main/java/cactus/slabslayer/Window.java#L51

**Comment by JVViacrusis** [comment]
Cause and solution for these lines in Window.java mentioned in https://github.com/COMP2522/project-cactus-club/issues/186#issuecomment-1493499306

Magic numbers are included in #206
