### ISSUE TITLE
Consider doing this on separate lines and fix magic numbers for readability

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-cactus-club#174]
https://github.com/COMP2522/project-cactus-club/blob/a55e24f504c6550cb517ed86f43152207fe107e3/src/main/java/cactus/slabslayer/Window.java#L50

**Comment by JVViacrusis** [comment]
Mentioned why this happened and how it was handled in https://github.com/COMP2522/project-cactus-club/issues/186#issuecomment-1493499306
