### ISSUE TITLE
GameElement class no usage, maybe this class name can be more clearly

### ISSUE THREAD

**Issue by NainZhou** [COMP2522/project-cactus-club#187]
https://github.com/COMP2522/project-cactus-club/blob/a55e24f504c6550cb517ed86f43152207fe107e3/src/main/java/cactus/slabslayer/Game.java#L6

**Comment by JVViacrusis** [comment]
GameElement is an abstract class, therefore no objects will be instantiated from it. Classes such as Slab, Ball, and Layout extend it.
